//json ví dụ nha mấy ô
const products = [
    {
        id: 104,
        title: "Apple iPhone Charger",
        description:
            "The Apple iPhone Charger is a high-quality charger designed for fast and efficient charging of your iPhone. Ensure your device stays powered up and ready to go.",
        brand: "Apple",
        category: "mobile-accessories",
        price: 19.99,
        discountPercentage: 18.52,
        rating: 4.15,
        stock: 31,
        availabilityStatus: "In Stock",
        sku: "MOB-APP-APP-104",
        minimumOrderQuantity: 14,
        returnPolicy: "90 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 2 weeks",
        tags: ["electronics", "chargers"],
        weight: 1,
        dimensions: { width: 13.63, height: 26.25, depth: 5.95 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/1.webp",
            "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/2.webp",
        ],
        meta: {
            createdAt: "2025-04-30T09:41:02.053Z",
            updatedAt: "2025-04-30T09:41:02.053Z",
            barcode: "0879776541417",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Excellent charger, works perfectly!",
                reviewerName: "John Doe",
            },
            {
                rating: 4,
                comment: "Charges fast, but cable is a bit short.",
                reviewerName: "Alice Nguyen",
            },
            {
                rating: 4.5,
                comment: "Good value for money.",
                reviewerName: "Michael Tran",
            },
        ],
    },
    {
        id: 105,
        title: "Apple MagSafe Battery Pack",
        description:
            "The Apple MagSafe Battery Pack is a portable and convenient way to add extra battery life to your MagSafe-compatible iPhone. Attach it magnetically for a secure connection.",
        brand: "Apple",
        category: "mobile-accessories",
        price: 99.99,
        discountPercentage: 17.17,
        rating: 3.62,
        stock: 1,
        availabilityStatus: "Low Stock",
        sku: "MOB-APP-APP-105",
        minimumOrderQuantity: 4,
        returnPolicy: "No return policy",
        warrantyInformation: "2 year warranty",
        shippingInformation: "Ships overnight",
        tags: ["electronics", "power banks"],
        weight: 6,
        dimensions: { width: 15.4, height: 11.89, depth: 19.67 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/1.webp",
            "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/2.webp",
        ],
        meta: {
            createdAt: "2025-04-30T09:41:02.053Z",
            updatedAt: "2025-04-30T09:41:02.053Z",
            barcode: "5157424897794",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 3,
                comment: "Battery life could be better.",
                reviewerName: "Minh Le",
            },
            {
                rating: 4,
                comment: "Handy for travel.",
                reviewerName: "Anna Pham",
            },
            {
                rating: 3.5,
                comment: "Good but a bit expensive.",
                reviewerName: "David Nguyen",
            },
        ],
    },
    {
        id: 107,
        title: "Beats Flex Wireless Earphones",
        description:
            "The Beats Flex Wireless Earphones offer a comfortable and versatile audio experience. With magnetic earbuds and up to 12 hours of battery life, they are ideal for everyday use.",
        brand: "Beats",
        category: "mobile-accessories",
        price: 49.99,
        discountPercentage: 5.73,
        rating: 4.24,
        stock: 50,
        availabilityStatus: "In Stock",
        sku: "MOB-BEA-BEA-107",
        minimumOrderQuantity: 17,
        returnPolicy: "7 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 1-2 business days",
        tags: ["electronics", "wireless earphones"],
        weight: 8,
        dimensions: { width: 17.86, height: 25.74, depth: 23.09 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/1.webp",
        ],
        meta: {
            createdAt: "2025-04-30T09:41:02.053Z",
            updatedAt: "2025-04-30T09:41:02.053Z",
            barcode: "1741271692174",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Excellent sound quality!",
                reviewerName: "Linh Pham",
            },
            {
                rating: 4,
                comment: "Very comfortable and stylish.",
                reviewerName: "Quang Tran",
            },
            {
                rating: 3.5,
                comment: "Good but battery drains fast.",
                reviewerName: "Nam Hoang",
            },
        ],
    },
    {
        id: 108,
        title: "iPhone 12 Silicone Case with MagSafe Plum",
        description:
            "The iPhone 12 Silicone Case with MagSafe in Plum is a stylish and protective case designed for the iPhone 12. It features MagSafe technology for easy attachment of accessories.",
        brand: "Apple",
        category: "mobile-accessories",
        price: 29.99,
        discountPercentage: 13.85,
        rating: 3.62,
        stock: 69,
        availabilityStatus: "In Stock",
        sku: "MOB-APP-IPH-108",
        minimumOrderQuantity: 4,
        returnPolicy: "90 days return policy",
        warrantyInformation: "3 months warranty",
        shippingInformation: "Ships in 3-5 business days",
        tags: ["electronics", "phone accessories"],
        weight: 7,
        dimensions: { width: 12.49, height: 11.29, depth: 23.52 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/1.webp",
            "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/2.webp",
            "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/3.webp",
            "https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/4.webp",
        ],
        meta: {
            createdAt: "2025-04-30T09:41:02.053Z",
            updatedAt: "2025-04-30T09:41:02.053Z",
            barcode: "8156838251449",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Fits perfectly and feels premium.",
                reviewerName: "Trang Vo",
            },
            {
                rating: 4,
                comment: "Color is beautiful and quality is nice.",
                reviewerName: "Bao Nguyen",
            },
            {
                rating: 3.5,
                comment: "A bit pricey for a case.",
                reviewerName: "Hai Dang",
            },
        ],
    },
    // --- 30 sản phẩm bổ sung ---
    {
        id: 109,
        title: "Samsung Galaxy Watch 6 Classic (47mm)",
        description:
            "Chiếc Samsung Galaxy Watch 6 Classic 47mm với thiết kế cổ điển, vòng bezel vật lý xoay, và các tính năng theo dõi sức khỏe tiên tiến.",
        brand: "Samsung",
        category: "smartwatches",
        price: 429.99,
        discountPercentage: 10.5,
        rating: 4.8,
        stock: 25,
        availabilityStatus: "In Stock",
        sku: "SMW-SAM-GW6-109",
        minimumOrderQuantity: 2,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 1 business day",
        tags: ["electronics", "wearables", "smartwatch"],
        weight: 60,
        dimensions: { width: 4.65, height: 4.65, depth: 1.09 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/smartwatches/samsung-galaxy-watch-6-classic-47mm/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/smartwatches/samsung-galaxy-watch-6-classic-47mm/1.webp",
            "https://cdn.dummyjson.com/product-images/smartwatches/samsung-galaxy-watch-6-classic-47mm/2.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:00:00.000Z",
            updatedAt: "2025-05-01T10:00:00.000Z",
            barcode: "8806094942704",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Thiết kế đẹp và nhiều tính năng hữu ích.",
                reviewerName: "Hoàng Minh",
            },
            {
                rating: 4.5,
                comment: "Rất hài lòng với thời lượng pin.",
                reviewerName: "Thanh Nga",
            },
        ],
    },
    {
        id: 110,
        title: "Sony WH-1000XM5 Noise Canceling Headphones",
        description:
            "Tai nghe chống ồn hàng đầu của Sony, mang lại trải nghiệm âm thanh tuyệt vời và khả năng cách âm vượt trội.",
        brand: "Sony",
        category: "headphones",
        price: 399.00,
        discountPercentage: 15.0,
        rating: 4.9,
        stock: 55,
        availabilityStatus: "In Stock",
        sku: "HEAD-SON-XM5-110",
        minimumOrderQuantity: 5,
        returnPolicy: "60 days return policy",
        warrantyInformation: "2 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "audio", "headphones"],
        weight: 250,
        dimensions: { width: 20.0, height: 16.0, depth: 8.0 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/headphones/sony-wh-1000xm5/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/headphones/sony-wh-1000xm5/1.webp",
            "https://cdn.dummyjson.com/product-images/headphones/sony-wh-1000xm5/2.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:05:00.000Z",
            updatedAt: "2025-05-01T10:05:00.000Z",
            barcode: "027242921006",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Chất lượng âm thanh tuyệt vời và chống ồn hiệu quả.",
                reviewerName: "Quang Le",
            },
            {
                rating: 5,
                comment: "Thoải mái khi đeo trong thời gian dài.",
                reviewerName: "Mai An",
            },
        ],
    },
    {
        id: 111,
        title: "Logitech MX Master 3S Wireless Mouse",
        description:
            "Chuột không dây cao cấp dành cho người làm việc chuyên nghiệp, có độ chính xác và tốc độ cuộn MagSpeed ấn tượng.",
        brand: "Logitech",
        category: "computer-accessories",
        price: 99.99,
        discountPercentage: 8.9,
        rating: 4.7,
        stock: 90,
        availabilityStatus: "In Stock",
        sku: "COMP-LOG-MXM3S-111",
        minimumOrderQuantity: 1,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 2 business days",
        tags: ["electronics", "peripherals", "mouse"],
        weight: 141,
        dimensions: { width: 8.43, height: 5.1, depth: 12.49 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/computer-accessories/logitech-mx-master-3s-mouse/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/computer-accessories/logitech-mx-master-3s-mouse/1.webp",
            "https://cdn.dummyjson.com/product-images/computer-accessories/logitech-mx-master-3s-mouse/2.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:10:00.000Z",
            updatedAt: "2025-05-01T10:10:00.000Z",
            barcode: "097855162464",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Chuột tốt nhất cho công việc. Rất thoải mái.",
                reviewerName: "Duy Kha",
            },
            {
                rating: 4,
                comment: "Giá hơi cao nhưng xứng đáng.",
                reviewerName: "Ngọc Lan",
            },
        ],
    },
    {
        id: 112,
        title: "Amazon Echo Dot (5th Gen) with Clock",
        description:
            "Loa thông minh với trợ lý ảo Alexa, tích hợp đồng hồ LED, lý tưởng cho phòng ngủ hoặc bàn làm việc.",
        brand: "Amazon",
        category: "smart-home",
        price: 59.99,
        discountPercentage: 12.2,
        rating: 4.6,
        stock: 120,
        availabilityStatus: "In Stock",
        sku: "SMH-AMZ-ED5C-112",
        minimumOrderQuantity: 10,
        returnPolicy: "90 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 3-5 business days",
        tags: ["electronics", "smart home", "speakers"],
        weight: 304,
        dimensions: { width: 10.0, height: 10.0, depth: 8.9 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/smart-home/amazon-echo-dot-5th-gen-clock/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/smart-home/amazon-echo-dot-5th-gen-clock/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:15:00.000Z",
            updatedAt: "2025-05-01T10:15:00.000Z",
            barcode: "840080590308",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Rất tiện lợi, chất lượng âm thanh ổn.",
                reviewerName: "Thanh Tùng",
            },
            {
                rating: 4,
                comment: "Dễ dàng thiết lập và sử dụng.",
                reviewerName: "Hải Anh",
            },
        ],
    },
    {
        id: 113,
        title: "Xiaomi Mi Smart Band 8",
        description:
            "Vòng đeo tay thông minh với màn hình AMOLED, theo dõi sức khỏe và thể thao, thời lượng pin dài.",
        brand: "Xiaomi",
        category: "wearables",
        price: 49.99,
        discountPercentage: 15.0,
        rating: 4.5,
        stock: 150,
        availabilityStatus: "In Stock",
        sku: "WEA-XIA-MB8-113",
        minimumOrderQuantity: 20,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 5 days",
        tags: ["electronics", "fitness tracker", "smart band"],
        weight: 27,
        dimensions: { width: 4.8, height: 2.25, depth: 1.1 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/wearables/xiaomi-mi-band-8/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/wearables/xiaomi-mi-band-8/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:20:00.000Z",
            updatedAt: "2025-05-01T10:20:00.000Z",
            barcode: "6934177770851",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Giá tốt, pin trâu, nhiều chế độ tập luyện.",
                reviewerName: "Bảo Trâm",
            },
        ],
    },
    {
        id: 114,
        title: "Apple TV 4K (3rd Gen)",
        description:
            "Thiết bị truyền phát trực tuyến với chất lượng hình ảnh 4K HDR, âm thanh Dolby Atmos và hệ sinh thái Apple.",
        brand: "Apple",
        category: "tv-accessories",
        price: 129.00,
        discountPercentage: 5.0,
        rating: 4.75,
        stock: 75,
        availabilityStatus: "In Stock",
        sku: "TVA-APP-TV4K-114",
        minimumOrderQuantity: 5,
        returnPolicy: "14 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "streaming", "media player"],
        weight: 208,
        dimensions: { width: 9.3, height: 9.3, depth: 3.1 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/tv-accessories/apple-tv-4k/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/tv-accessories/apple-tv-4k/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:25:00.000Z",
            updatedAt: "2025-05-01T10:25:00.000Z",
            barcode: "0879776541418",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Tốc độ nhanh, giao diện mượt mà.",
                reviewerName: "Huy Cường",
            },
        ],
    },
    {
        id: 115,
        title: "SanDisk Ultra 128GB MicroSD Card",
        description:
            "Thẻ nhớ MicroSD dung lượng 128GB, tốc độ cao, lý tưởng cho điện thoại thông minh và máy ảnh.",
        brand: "SanDisk",
        category: "storage",
        price: 19.99,
        discountPercentage: 20.0,
        rating: 4.65,
        stock: 300,
        availabilityStatus: "In Stock",
        sku: "STO-SAN-USD128-115",
        minimumOrderQuantity: 50,
        returnPolicy: "30 days return policy",
        warrantyInformation: "10 year limited warranty",
        shippingInformation: "Ships in 1-3 business days",
        tags: ["electronics", "memory", "storage"],
        weight: 0.5,
        dimensions: { width: 1.5, height: 1.1, depth: 0.1 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/storage/sandisk-microsd-card/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/storage/sandisk-microsd-card/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:30:00.000Z",
            updatedAt: "2025-05-01T10:30:00.000Z",
            barcode: "619659104113",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Hoạt động hoàn hảo với máy ảnh của tôi.",
                reviewerName: "Văn Đức",
            },
        ],
    },
    {
        id: 116,
        title: "JBL Flip 6 Portable Bluetooth Speaker",
        description:
            "Loa Bluetooth di động với âm thanh mạnh mẽ, chống nước IP67, thời lượng pin 12 giờ.",
        brand: "JBL",
        category: "speakers",
        price: 129.95,
        discountPercentage: 10.0,
        rating: 4.8,
        stock: 45,
        availabilityStatus: "In Stock",
        sku: "SPE-JBL-FLIP6-116",
        minimumOrderQuantity: 3,
        returnPolicy: "60 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "audio", "speaker"],
        weight: 550,
        dimensions: { width: 17.8, height: 6.8, depth: 7.2 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/speakers/jbl-flip-6/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/speakers/jbl-flip-6/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:35:00.000Z",
            updatedAt: "2025-05-01T10:35:00.000Z",
            barcode: "050036380625",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Âm bass mạnh mẽ, rất thích hợp cho tiệc ngoài trời.",
                reviewerName: "Minh Quân",
            },
        ],
    },
    {
        id: 117,
        title: "Acer Nitro 5 Gaming Laptop",
        description:
            "Laptop chơi game mạnh mẽ với CPU Intel Core i7, GPU NVIDIA GeForce RTX 4050, màn hình 144Hz.",
        brand: "Acer",
        category: "laptops",
        price: 1299.00,
        discountPercentage: 18.0,
        rating: 4.3,
        stock: 15,
        availabilityStatus: "Limited Stock",
        sku: "LAP-ACE-N5-117",
        minimumOrderQuantity: 1,
        returnPolicy: "14 days return policy",
        warrantyInformation: "2 year warranty",
        shippingInformation: "Ships in 3 business days",
        tags: ["electronics", "pc", "gaming"],
        weight: 2200,
        dimensions: { width: 36.3, height: 27.2, depth: 2.7 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/laptops/acer-nitro-5/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/laptops/acer-nitro-5/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:40:00.000Z",
            updatedAt: "2025-05-01T10:40:00.000Z",
            barcode: "4711123456789",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 4,
                comment: "Hiệu năng tốt, quạt hơi ồn khi chơi game nặng.",
                reviewerName: "Khánh Duy",
            },
        ],
    },
    {
        id: 118,
        title: "Canon EOS R10 Mirrorless Camera",
        description:
            "Máy ảnh mirrorless nhỏ gọn, cảm biến APS-C, lấy nét tự động Dual Pixel CMOS AF II, quay video 4K.",
        brand: "Canon",
        category: "cameras",
        price: 979.00,
        discountPercentage: 10.0,
        rating: 4.7,
        stock: 20,
        availabilityStatus: "In Stock",
        sku: "CAM-CAN-R10-118",
        minimumOrderQuantity: 2,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 1-2 business days",
        tags: ["electronics", "photography", "camera"],
        weight: 429,
        dimensions: { width: 12.25, height: 8.78, depth: 8.34 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/cameras/canon-eos-r10/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/cameras/canon-eos-r10/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:45:00.000Z",
            updatedAt: "2025-05-01T10:45:00.000Z",
            barcode: "4549292198084",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Máy ảnh tuyệt vời cho người mới bắt đầu.",
                reviewerName: "Thu Hà",
            },
        ],
    },
    {
        id: 119,
        title: "Apple AirPods Pro (2nd Gen)",
        description:
            "Tai nghe không dây chống ồn chủ động, chế độ Transparency, âm thanh không gian cá nhân hóa.",
        brand: "Apple",
        category: "headphones",
        price: 249.00,
        discountPercentage: 10.0,
        rating: 4.85,
        stock: 80,
        availabilityStatus: "In Stock",
        sku: "HEAD-APP-AP2-119",
        minimumOrderQuantity: 5,
        returnPolicy: "14 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "wireless earbuds", "audio"],
        weight: 5.3,
        dimensions: { width: 2.18, height: 3.09, depth: 2.4 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/headphones/apple-airpods-pro-2nd-gen/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/headphones/apple-airpods-pro-2nd-gen/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:50:00.000Z",
            updatedAt: "2025-05-01T10:50:00.000Z",
            barcode: "194253303831",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Chất lượng âm thanh và chống ồn đỉnh cao.",
                reviewerName: "Nam Cao",
            },
        ],
    },
    {
        id: 120,
        title: "Xiaomi 13T Pro",
        description:
            "Điện thoại thông minh flagship với hệ thống camera Leica, chip Dimensity 9200+, sạc nhanh 120W.",
        brand: "Xiaomi",
        category: "smartphones",
        price: 799.00,
        discountPercentage: 15.0,
        rating: 4.6,
        stock: 35,
        availabilityStatus: "In Stock",
        sku: "SMT-XIA-13TP-120",
        minimumOrderQuantity: 1,
        returnPolicy: "30 days return policy",
        warrantyInformation: "2 year warranty",
        shippingInformation: "Ships in 2 business days",
        tags: ["electronics", "mobile", "android"],
        weight: 200,
        dimensions: { width: 162.2, height: 75.7, depth: 8.5 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/smartphones/xiaomi-13t-pro/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/smartphones/xiaomi-13t-pro/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T10:55:00.000Z",
            updatedAt: "2025-05-01T10:55:00.000Z",
            barcode: "6934177770852",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Hiệu năng cực mạnh, sạc siêu nhanh.",
                reviewerName: "Tuấn Anh",
            },
        ],
    },
    {
        id: 121,
        title: "Apple Watch SE (2nd Gen)",
        description:
            "Đồng hồ thông minh giá phải chăng của Apple, có theo dõi sức khỏe và an toàn, kết nối di động.",
        brand: "Apple",
        category: "smartwatches",
        price: 249.00,
        discountPercentage: 8.0,
        rating: 4.5,
        stock: 60,
        availabilityStatus: "In Stock",
        sku: "SMW-APP-WSE2-121",
        minimumOrderQuantity: 3,
        returnPolicy: "14 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 1-2 business days",
        tags: ["electronics", "wearables", "smartwatch"],
        weight: 36.2,
        dimensions: { width: 44.0, height: 38.0, depth: 10.7 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/smartwatches/apple-watch-se-2nd-gen/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/smartwatches/apple-watch-se-2nd-gen/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:00:00.000Z",
            updatedAt: "2025-05-01T11:00:00.000Z",
            barcode: "1942536412345",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 4,
                comment: "Tốt cho việc tập thể dục hàng ngày.",
                reviewerName: "Minh Thu",
            },
        ],
    },
    {
        id: 122,
        title: "Logitech K380 Multi-Device Bluetooth Keyboard",
        description:
            "Bàn phím Bluetooth nhỏ gọn, có thể kết nối với 3 thiết bị khác nhau, tương thích đa nền tảng.",
        brand: "Logitech",
        category: "computer-accessories",
        price: 39.99,
        discountPercentage: 10.0,
        rating: 4.4,
        stock: 100,
        availabilityStatus: "In Stock",
        sku: "COMP-LOG-K380-122",
        minimumOrderQuantity: 10,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 2 business days",
        tags: ["electronics", "peripherals", "keyboard"],
        weight: 423,
        dimensions: { width: 27.9, height: 12.4, depth: 1.6 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/computer-accessories/logitech-k380-keyboard/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/computer-accessories/logitech-k380-keyboard/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:05:00.000Z",
            updatedAt: "2025-05-01T11:05:00.000Z",
            barcode: "5099206066297",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Rất thích hợp cho việc di chuyển, gõ êm.",
                reviewerName: "Hoàng Long",
            },
        ],
    },
    {
        id: 123,
        title: "Amazon Fire TV Stick 4K Max",
        description:
            "Thiết bị truyền phát trực tuyến hỗ trợ 4K Ultra HD, Wi-Fi 6 và tích hợp Alexa.",
        brand: "Amazon",
        category: "tv-accessories",
        price: 54.99,
        discountPercentage: 15.0,
        rating: 4.6,
        stock: 110,
        availabilityStatus: "In Stock",
        sku: "TVA-AMZ-FTS4KM-123",
        minimumOrderQuantity: 5,
        returnPolicy: "90 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 3 days",
        tags: ["electronics", "streaming", "media player"],
        weight: 48,
        dimensions: { width: 10.8, height: 3.0, depth: 1.4 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/tv-accessories/amazon-fire-tv-stick-4k-max/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/tv-accessories/amazon-fire-tv-stick-4k-max/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:10:00.000Z",
            updatedAt: "2025-05-01T11:10:00.000Z",
            barcode: "840080590309",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 4.5,
                comment: "Tốc độ phản hồi nhanh, chất lượng hình ảnh tuyệt vời.",
                reviewerName: "Diệu Linh",
            },
        ],
    },
    {
        id: 124,
        title: "Samsung T7 Portable SSD 1TB",
        description:
            "Ổ cứng SSD di động dung lượng 1TB, tốc độ đọc/ghi nhanh, thiết kế nhỏ gọn và bền bỉ.",
        brand: "Samsung",
        category: "storage",
        price: 119.99,
        discountPercentage: 25.0,
        rating: 4.8,
        stock: 80,
        availabilityStatus: "In Stock",
        sku: "STO-SAM-T7-124",
        minimumOrderQuantity: 4,
        returnPolicy: "60 days return policy",
        warrantyInformation: "3 year limited warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "storage", "ssd"],
        weight: 58,
        dimensions: { width: 8.5, height: 5.7, depth: 0.8 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/storage/samsung-t7-ssd/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/storage/samsung-t7-ssd/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:15:00.000Z",
            updatedAt: "2025-05-01T11:15:00.000Z",
            barcode: "8806090403362",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Tốc độ truyền dữ liệu rất nhanh.",
                reviewerName: "Quốc Bảo",
            },
        ],
    },
    {
        id: 125,
        title: "Bose QuietComfort Earbuds II",
        description:
            "Tai nghe không dây chống ồn với công nghệ CustomTune, mang lại âm thanh sống động và khả năng chống ồn cá nhân hóa.",
        brand: "Bose",
        category: "headphones",
        price: 279.00,
        discountPercentage: 10.0,
        rating: 4.7,
        stock: 40,
        availabilityStatus: "In Stock",
        sku: "HEAD-BOS-QCE2-125",
        minimumOrderQuantity: 5,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 1-2 business days",
        tags: ["electronics", "wireless earbuds", "audio"],
        weight: 6.2,
        dimensions: { width: 3.0, height: 4.0, depth: 3.0 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/headphones/bose-quietcomfort-earbuds-ii/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/headphones/bose-quietcomfort-earbuds-ii/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:20:00.000Z",
            updatedAt: "2025-05-01T11:20:00.000Z",
            barcode: "017817830588",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Chống ồn tốt nhất tôi từng dùng.",
                reviewerName: "Trần Anh",
            },
        ],
    },
    {
        id: 126,
        title: "Dell XPS 13 Plus Laptop",
        description:
            "Laptop cao cấp với thiết kế hiện đại, màn hình InfinityEdge, hiệu năng mạnh mẽ.",
        brand: "Dell",
        category: "laptops",
        price: 1599.00,
        discountPercentage: 20.0,
        rating: 4.5,
        stock: 10,
        availabilityStatus: "Limited Stock",
        sku: "LAP-DEL-XP13P-126",
        minimumOrderQuantity: 1,
        returnPolicy: "14 days return policy",
        warrantyInformation: "3 year warranty",
        shippingInformation: "Ships in 5 business days",
        tags: ["electronics", "pc", "ultrabook"],
        weight: 1240,
        dimensions: { width: 29.5, height: 19.9, depth: 1.53 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/laptops/dell-xps-13-plus/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/laptops/dell-xps-13-plus/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:25:00.000Z",
            updatedAt: "2025-05-01T11:25:00.000Z",
            barcode: "884116428453",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 4,
                comment: "Thiết kế đẹp, hiệu năng ổn định, nhưng hơi nóng.",
                reviewerName: "Đức Thịnh",
            },
        ],
    },
    {
        id: 127,
        title: "GoPro HERO12 Black Action Camera",
        description:
            "Máy quay hành động chống nước, quay video 5.3K60, ổn định hình ảnh HyperSmooth 6.0.",
        brand: "GoPro",
        category: "cameras",
        price: 399.99,
        discountPercentage: 12.0,
        rating: 4.9,
        stock: 30,
        availabilityStatus: "In Stock",
        sku: "CAM-GOP-H12-127",
        minimumOrderQuantity: 3,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "action camera", "photography"],
        weight: 154,
        dimensions: { width: 7.1, height: 5.5, depth: 3.36 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/cameras/gopro-hero12-black/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/cameras/gopro-hero12-black/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:30:00.000Z",
            updatedAt: "2025-05-01T11:30:00.000Z",
            barcode: "818279029707",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Chất lượng video xuất sắc và rất bền.",
                reviewerName: "Hoàng Duy",
            },
        ],
    },
    {
        id: 128,
        title: "Apple HomePod (2nd Gen)",
        description:
            "Loa thông minh với âm thanh chất lượng cao, tích hợp Siri, trung tâm điều khiển nhà thông minh.",
        brand: "Apple",
        category: "smart-home",
        price: 299.00,
        discountPercentage: 5.0,
        rating: 4.4,
        stock: 50,
        availabilityStatus: "In Stock",
        sku: "SMH-APP-HP2-128",
        minimumOrderQuantity: 2,
        returnPolicy: "14 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 2-3 business days",
        tags: ["electronics", "smart home", "speakers"],
        weight: 2300,
        dimensions: { width: 14.2, height: 16.8, depth: 14.2 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/smart-home/apple-homepod-2nd-gen/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/smart-home/apple-homepod-2nd-gen/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:35:00.000Z",
            updatedAt: "2025-05-01T11:35:00.000Z",
            barcode: "1942530123456",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 4,
                comment: "Âm thanh hay, nhưng chỉ hoạt động tốt với thiết bị Apple.",
                reviewerName: "Thùy Trang",
            },
        ],
    },
    {
        id: 129,
        title: "Samsung Galaxy Buds2 Pro",
        description:
            "Tai nghe không dây chống ồn với âm thanh 24-bit Hi-Fi, thiết kế công thái học.",
        brand: "Samsung",
        category: "headphones",
        price: 229.99,
        discountPercentage: 15.0,
        rating: 4.6,
        stock: 70,
        availabilityStatus: "In Stock",
        sku: "HEAD-SAM-GB2P-129",
        minimumOrderQuantity: 5,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "wireless earbuds", "audio"],
        weight: 5.5,
        dimensions: { width: 17.0, height: 17.9, depth: 20.9 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/headphones/samsung-galaxy-buds2-pro/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/headphones/samsung-galaxy-buds2-pro/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:40:00.000Z",
            updatedAt: "2025-05-01T11:40:00.000Z",
            barcode: "8806094942705",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Rất phù hợp với điện thoại Samsung, âm thanh rõ nét.",
                reviewerName: "Kim Anh",
            },
        ],
    },
    {
        id: 130,
        title: "Apple 20W USB-C Power Adapter",
        description:
            "Củ sạc USB-C 20W nhỏ gọn, cung cấp khả năng sạc nhanh cho iPhone và các thiết bị khác.",
        brand: "Apple",
        category: "mobile-accessories",
        price: 19.00,
        discountPercentage: 10.0,
        rating: 4.5,
        stock: 150,
        availabilityStatus: "In Stock",
        sku: "MOB-APP-AD20W-130",
        minimumOrderQuantity: 10,
        returnPolicy: "90 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 1 business day",
        tags: ["electronics", "chargers", "adapter"],
        weight: 50,
        dimensions: { width: 4.5, height: 4.5, depth: 3.0 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-20w-usb-c-power-adapter/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-20w-usb-c-power-adapter/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:45:00.000Z",
            updatedAt: "2025-05-01T11:45:00.000Z",
            barcode: "1942521234567",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 4.5,
                comment: "Sạc nhanh, hàng chính hãng nên yên tâm.",
                reviewerName: "Phú Cường",
            },
        ],
    },
    {
        id: 131,
        title: "Razer BlackWidow V4 Pro Mechanical Keyboard",
        description:
            "Bàn phím cơ chơi game với switch cơ tùy chỉnh, đèn nền Razer Chroma RGB, các phím macro chuyên dụng.",
        brand: "Razer",
        category: "computer-accessories",
        price: 229.99,
        discountPercentage: 15.0,
        rating: 4.7,
        stock: 25,
        availabilityStatus: "In Stock",
        sku: "COMP-RAZ-BWV4P-131",
        minimumOrderQuantity: 2,
        returnPolicy: "30 days return policy",
        warrantyInformation: "2 year warranty",
        shippingInformation: "Ships in 3 business days",
        tags: ["electronics", "peripherals", "gaming keyboard"],
        weight: 1500,
        dimensions: { width: 45.1, height: 15.9, depth: 4.4 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/computer-accessories/razer-blackwidow-v4-pro/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/computer-accessories/razer-blackwidow-v4-pro/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:50:00.000Z",
            updatedAt: "2025-05-01T11:50:00.000Z",
            barcode: "8886419358117",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Cảm giác gõ tuyệt vời, đèn RGB rất đẹp.",
                reviewerName: "Gia Huy",
            },
        ],
    },
    {
        id: 132,
        title: "Nintendo Switch OLED Model",
        description:
            "Máy chơi game cầm tay và tại gia với màn hình OLED 7 inch rực rỡ, bộ nhớ trong 64GB, chân đế rộng hơn.",
        brand: "Nintendo",
        category: "gaming",
        price: 349.99,
        discountPercentage: 5.0,
        rating: 4.9,
        stock: 50,
        availabilityStatus: "In Stock",
        sku: "GAM-NIN-SWOLED-132",
        minimumOrderQuantity: 1,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "console", "gaming"],
        weight: 420,
        dimensions: { width: 24.2, height: 13.7, depth: 1.39 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/gaming/nintendo-switch-oled/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/gaming/nintendo-switch-oled/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T11:55:00.000Z",
            updatedAt: "2025-05-01T11:55:00.000Z",
            barcode: "0454964531235",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Màn hình OLED quá đẹp, trải nghiệm chơi game tuyệt vời.",
                reviewerName: "Thanh Hải",
            },
        ],
    },
    {
        id: 133,
        title: "WD Elements 2TB Portable External Hard Drive",
        description:
            "Ổ cứng ngoài 2TB USB 3.0, dung lượng lớn, dễ dàng mang theo, tốc độ truyền dữ liệu nhanh.",
        brand: "Western Digital",
        category: "storage",
        price: 79.99,
        discountPercentage: 20.0,
        rating: 4.5,
        stock: 150,
        availabilityStatus: "In Stock",
        sku: "STO-WD-EL2TB-133",
        minimumOrderQuantity: 10,
        returnPolicy: "90 days return policy",
        warrantyInformation: "2 year warranty",
        shippingInformation: "Ships in 3 days",
        tags: ["electronics", "storage", "hard drive"],
        weight: 130,
        dimensions: { width: 11.0, height: 8.2, depth: 1.5 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/storage/wd-elements-2tb/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/storage/wd-elements-2tb/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:00:00.000Z",
            updatedAt: "2025-05-01T12:00:00.000Z",
            barcode: "718037848243",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 4,
                comment: "Dung lượng lớn, giá phải chăng.",
                reviewerName: "Văn Hùng",
            },
        ],
    },
    {
        id: 134,
        title: "Samsung Galaxy Tab S9 Ultra",
        description:
            "Máy tính bảng cao cấp với màn hình Dynamic AMOLED 2X lớn, bút S Pen đi kèm, hiệu năng mạnh mẽ.",
        brand: "Samsung",
        category: "tablets",
        price: 1199.00,
        discountPercentage: 10.0,
        rating: 4.7,
        stock: 20,
        availabilityStatus: "Limited Stock",
        sku: "TAB-SAM-S9U-134",
        minimumOrderQuantity: 1,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 2 business days",
        tags: ["electronics", "tablet", "android"],
        weight: 732,
        dimensions: { width: 32.64, height: 20.86, depth: 0.55 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s9-ultra/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s9-ultra/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:05:00.000Z",
            updatedAt: "2025-05-01T12:05:00.000Z",
            barcode: "8806094942706",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Màn hình lớn tuyệt đẹp, rất tốt cho công việc và giải trí.",
                reviewerName: "Minh Dũng",
            },
        ],
    },
    {
        id: 135,
        title: "Apple Pencil (2nd Generation)",
        description:
            "Bút cảm ứng thế hệ thứ 2 của Apple, kết nối từ tính và sạc không dây với iPad Pro/Air tương thích.",
        brand: "Apple",
        category: "mobile-accessories",
        price: 129.00,
        discountPercentage: 5.0,
        rating: 4.6,
        stock: 75,
        availabilityStatus: "In Stock",
        sku: "MOB-APP-AP2-135",
        minimumOrderQuantity: 5,
        returnPolicy: "14 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "stylus", "accessories"],
        weight: 20.7,
        dimensions: { width: 16.6, height: 0.89, depth: 0.89 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-pencil-2nd-gen/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-pencil-2nd-gen/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:10:00.000Z",
            updatedAt: "2025-05-01T12:10:00.000Z",
            barcode: "1942521234568",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Độ trễ thấp, cảm giác viết rất tự nhiên.",
                reviewerName: "Bích Vân",
            },
        ],
    },
    {
        id: 136,
        title: "Google Nest Hub (2nd Gen)",
        description:
            "Màn hình thông minh với trợ lý Google, theo dõi giấc ngủ, và điều khiển các thiết bị nhà thông minh.",
        brand: "Google",
        category: "smart-home",
        price: 99.99,
        discountPercentage: 15.0,
        rating: 4.5,
        stock: 90,
        availabilityStatus: "In Stock",
        sku: "SMH-GOO-NH2-136",
        minimumOrderQuantity: 5,
        returnPolicy: "90 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 3-5 business days",
        tags: ["electronics", "smart home", "display"],
        weight: 558,
        dimensions: { width: 17.74, height: 12.04, depth: 6.95 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/smart-home/google-nest-hub-2nd-gen/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/smart-home/google-nest-hub-2nd-gen/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:15:00.000Z",
            updatedAt: "2025-05-01T12:15:00.000Z",
            barcode: "193575006622",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 4,
                comment: "Màn hình đẹp, theo dõi giấc ngủ khá chính xác.",
                reviewerName: "Nguyễn Trung",
            },
        ],
    },
    {
        id: 137,
        title: "Anker PowerCore III Elite 25600",
        description:
            "Pin sạc dự phòng dung lượng lớn 25600mAh, công suất 87W, sạc nhanh cho laptop và các thiết bị khác.",
        brand: "Anker",
        category: "mobile-accessories",
        price: 159.99,
        discountPercentage: 10.0,
        rating: 4.8,
        stock: 50,
        availabilityStatus: "In Stock",
        sku: "MOB-ANK-PC3E-137",
        minimumOrderQuantity: 5,
        returnPolicy: "30 days return policy",
        warrantyInformation: "18 months warranty",
        shippingInformation: "Ships in 1-2 business days",
        tags: ["electronics", "power banks", "chargers"],
        weight: 574,
        dimensions: { width: 18.3, height: 8.2, depth: 2.4 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/mobile-accessories/anker-powercore-iii-elite-25600/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/mobile-accessories/anker-powercore-iii-elite-25600/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:20:00.000Z",
            updatedAt: "2025-05-01T12:20:00.000Z",
            barcode: "848061078709",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Sạc được laptop, rất mạnh mẽ và bền.",
                reviewerName: "Công Minh",
            },
        ],
    },
    {
        id: 138,
        title: "Logitech StreamCam Full HD Webcam",
        description:
            "Webcam Full HD 1080p 60fps, tự động lấy nét và phơi sáng thông minh, tối ưu cho streamer và người sáng tạo nội dung.",
        brand: "Logitech",
        category: "computer-accessories",
        price: 169.99,
        discountPercentage: 20.0,
        rating: 4.6,
        stock: 40,
        availabilityStatus: "In Stock",
        sku: "COMP-LOG-SC-138",
        minimumOrderQuantity: 5,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 2 business days",
        tags: ["electronics", "peripherals", "webcam"],
        weight: 150,
        dimensions: { width: 8.5, height: 4.8, depth: 4.8 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/computer-accessories/logitech-streamcam/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/computer-accessories/logitech-streamcam/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:25:00.000Z",
            updatedAt: "2025-05-01T12:25:00.000Z",
            barcode: "097855162465",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Chất lượng hình ảnh sắc nét, rất chuyên nghiệp.",
                reviewerName: "Bảo Ngọc",
            },
        ],
    },
    {
        id: 139,
        title: "Samsung QN90C Neo QLED 4K Smart TV (65 inch)",
        description:
            "Smart TV 65 inch với công nghệ Neo QLED 4K, Mini LED, Tần số quét 144Hz, âm thanh Dolby Atmos.",
        brand: "Samsung",
        category: "televisions",
        price: 2699.00,
        discountPercentage: 25.0,
        rating: 4.8,
        stock: 12,
        availabilityStatus: "Limited Stock",
        sku: "TV-SAM-QN90C-139",
        minimumOrderQuantity: 1,
        returnPolicy: "30 days return policy",
        warrantyInformation: "3 year warranty",
        shippingInformation: "Ships in 5-7 business days",
        tags: ["electronics", "tv", "smart tv"],
        weight: 24200,
        dimensions: { width: 144.6, height: 89.4, depth: 25.7 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/televisions/samsung-qn90c-65-inch/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/televisions/samsung-qn90c-65-inch/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:30:00.000Z",
            updatedAt: "2025-05-01T12:30:00.000Z",
            barcode: "8806094942707",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Chất lượng hình ảnh đỉnh cao, màu sắc rực rỡ.",
                reviewerName: "Văn Sĩ",
            },
        ],
    },
    {
        id: 140,
        title: "Apple Watch Ultra 2",
        description:
            "Đồng hồ thông minh bền bỉ nhất của Apple, GPS chính xác cao, thời lượng pin 36 giờ, vỏ titan.",
        brand: "Apple",
        category: "smartwatches",
        price: 799.00,
        discountPercentage: 5.0,
        rating: 4.9,
        stock: 30,
        availabilityStatus: "In Stock",
        sku: "SMW-APP-WU2-140",
        minimumOrderQuantity: 2,
        returnPolicy: "14 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "wearables", "smartwatch", "outdoor"],
        weight: 61.4,
        dimensions: { width: 49.0, height: 44.0, depth: 14.4 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/smartwatches/apple-watch-ultra-2/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/smartwatches/apple-watch-ultra-2/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:35:00.000Z",
            updatedAt: "2025-05-01T12:35:00.000Z",
            barcode: "1942531234569",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Bền bỉ, pin lâu, rất tốt cho thể thao mạo hiểm.",
                reviewerName: "Hoàng Kiên",
            },
        ],
    },
    {
        id: 141,
        title: "DJI Mini 4 Pro Drone",
        description:
            "Flycam mini dưới 249g, cảm biến phát hiện chướng ngại vật đa hướng, quay video 4K/60fps HDR.",
        brand: "DJI",
        category: "drones",
        price: 759.00,
        discountPercentage: 10.0,
        rating: 4.8,
        stock: 15,
        availabilityStatus: "Limited Stock",
        sku: "DRO-DJI-M4P-141",
        minimumOrderQuantity: 1,
        returnPolicy: "14 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 3 business days",
        tags: ["electronics", "photography", "drone"],
        weight: 249,
        dimensions: { width: 14.5, height: 9.0, depth: 6.0 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/drones/dji-mini-4-pro/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/drones/dji-mini-4-pro/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:40:00.000Z",
            updatedAt: "2025-05-01T12:40:00.000Z",
            barcode: "6941565961234",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Chất lượng hình ảnh tuyệt vời, rất dễ điều khiển.",
                reviewerName: "Khắc Việt",
            },
        ],
    },
    {
        id: 142,
        title: "Philips Hue White and Color Ambiance Starter Kit",
        description:
            "Bộ khởi động đèn thông minh, gồm 3 bóng đèn và 1 Bridge, 16 triệu màu, điều khiển qua ứng dụng.",
        brand: "Philips Hue",
        category: "smart-home",
        price: 199.99,
        discountPercentage: 15.0,
        rating: 4.6,
        stock: 60,
        availabilityStatus: "In Stock",
        sku: "SMH-PHI-HWCSK-142",
        minimumOrderQuantity: 5,
        returnPolicy: "90 days return policy",
        warrantyInformation: "2 year warranty",
        shippingInformation: "Ships in 1-2 business days",
        tags: ["electronics", "smart home", "lighting"],
        weight: 600,
        dimensions: { width: 12.0, height: 10.0, depth: 10.0 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/smart-home/philips-hue-starter-kit/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/smart-home/philips-hue-starter-kit/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:45:00.000Z",
            updatedAt: "2025-05-01T12:45:00.000Z",
            barcode: "046677457754",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 4.5,
                comment: "Rất dễ cài đặt, tạo không khí ấm cúng.",
                reviewerName: "Mai Phương",
            },
        ],
    },
    {
        id: 143,
        title: "HP LaserJet Pro M15w Wireless Printer",
        description:
            "Máy in laser trắng đen nhỏ gọn, in không dây qua Wi-Fi, tốc độ in nhanh.",
        brand: "HP",
        category: "printers",
        price: 119.99,
        discountPercentage: 18.0,
        rating: 4.3,
        stock: 45,
        availabilityStatus: "In Stock",
        sku: "PRI-HP-M15W-143",
        minimumOrderQuantity: 5,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 3 business days",
        tags: ["electronics", "office", "printer"],
        weight: 3800,
        dimensions: { width: 34.5, height: 18.9, depth: 15.8 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/printers/hp-laserjet-pro-m15w/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/printers/hp-laserjet-pro-m15w/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:50:00.000Z",
            updatedAt: "2025-05-01T12:50:00.000Z",
            barcode: "1907812345678",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 4,
                comment: "In nhanh, phù hợp cho văn phòng nhỏ.",
                reviewerName: "Xuân Nam",
            },
        ],
    },
    {
        id: 144,
        title: "Sony PlayStation 5 Slim Console",
        description:
            "Máy chơi game thế hệ mới của Sony, thiết kế mỏng hơn, ổ SSD tốc độ cao, đồ họa 4K.",
        brand: "Sony",
        category: "gaming",
        price: 499.99,
        discountPercentage: 5.0,
        rating: 4.9,
        stock: 50,
        availabilityStatus: "In Stock",
        sku: "GAM-SON-PS5S-144",
        minimumOrderQuantity: 1,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "console", "gaming"],
        weight: 3200,
        dimensions: { width: 35.8, height: 9.6, depth: 21.6 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/gaming/sony-ps5-slim/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/gaming/sony-ps5-slim/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T12:55:00.000Z",
            updatedAt: "2025-05-01T12:55:00.000Z",
            barcode: "0711719572626",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Trải nghiệm chơi game tuyệt vời, tải game rất nhanh.",
                reviewerName: "Đình Hiếu",
            },
        ],
    },
    {
        id: 145,
        title: "Anker PowerLine II USB-C to Lightning Cable (6ft)",
        description:
            "Cáp sạc USB-C to Lightning bền bỉ, hỗ trợ sạc nhanh, chứng nhận MFi.",
        brand: "Anker",
        category: "mobile-accessories",
        price: 21.99,
        discountPercentage: 10.0,
        rating: 4.7,
        stock: 200,
        availabilityStatus: "In Stock",
        sku: "MOB-ANK-PL2-145",
        minimumOrderQuantity: 15,
        returnPolicy: "Lifetime warranty",
        warrantyInformation: "Lifetime warranty",
        shippingInformation: "Ships in 1 business day",
        tags: ["electronics", "cables", "chargers"],
        weight: 30,
        dimensions: { width: 1.5, height: 180.0, depth: 0.5 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/mobile-accessories/anker-powerline-ii-cable/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/mobile-accessories/anker-powerline-ii-cable/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T13:00:00.000Z",
            updatedAt: "2025-05-01T13:00:00.000Z",
            barcode: "848061078710",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Cáp rất bền, sạc nhanh ổn định.",
                reviewerName: "Phan Anh",
            },
        ],
    },
    {
        id: 146,
        title: "Razer DeathAdder V3 Pro Wireless Gaming Mouse",
        description:
            "Chuột chơi game không dây siêu nhẹ, cảm biến quang học Focus Pro 30K, tốc độ 4000Hz.",
        brand: "Razer",
        category: "computer-accessories",
        price: 159.99,
        discountPercentage: 10.0,
        rating: 4.8,
        stock: 35,
        availabilityStatus: "In Stock",
        sku: "COMP-RAZ-DAV3P-146",
        minimumOrderQuantity: 3,
        returnPolicy: "30 days return policy",
        warrantyInformation: "2 year warranty",
        shippingInformation: "Ships in 2 business days",
        tags: ["electronics", "peripherals", "gaming mouse"],
        weight: 63,
        dimensions: { width: 12.8, height: 6.8, depth: 4.4 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/computer-accessories/razer-deathadder-v3-pro/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/computer-accessories/razer-deathadder-v3-pro/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T13:05:00.000Z",
            updatedAt: "2025-05-01T13:05:00.000Z",
            barcode: "8886419358118",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Cực kỳ nhẹ, tốc độ phản hồi siêu nhanh.",
                reviewerName: "Thành Đạt",
            },
        ],
    },
    {
        id: 147,
        title: "Samsung Galaxy S24 Ultra",
        description:
            "Điện thoại thông minh flagship với chip Snapdragon 8 Gen 3 for Galaxy, camera 200MP, và bút S Pen tích hợp.",
        brand: "Samsung",
        category: "smartphones",
        price: 1299.00,
        discountPercentage: 8.0,
        rating: 4.9,
        stock: 25,
        availabilityStatus: "In Stock",
        sku: "SMT-SAM-S24U-147",
        minimumOrderQuantity: 1,
        returnPolicy: "30 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "mobile", "android"],
        weight: 232,
        dimensions: { width: 162.3, height: 79.0, depth: 8.6 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s24-ultra/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s24-ultra/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T13:10:00.000Z",
            updatedAt: "2025-05-01T13:10:00.000Z",
            barcode: "8806094942708",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Camera tuyệt vời, các tính năng AI rất hữu ích.",
                reviewerName: "Thế Anh",
            },
        ],
    },
    {
        id: 148,
        title: "Logitech Z623 THX-Certified 2.1 Speaker System",
        description:
            "Hệ thống loa 2.1 với âm thanh mạnh mẽ 400 Watt, chứng nhận THX, lý tưởng cho máy tính và TV.",
        brand: "Logitech",
        category: "speakers",
        price: 149.99,
        discountPercentage: 15.0,
        rating: 4.6,
        stock: 40,
        availabilityStatus: "In Stock",
        sku: "SPE-LOG-Z623-148",
        minimumOrderQuantity: 3,
        returnPolicy: "30 days return policy",
        warrantyInformation: "2 year warranty",
        shippingInformation: "Ships in 2-3 business days",
        tags: ["electronics", "audio", "speakers"],
        weight: 7000,
        dimensions: { width: 30.0, height: 26.5, depth: 28.4 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/speakers/logitech-z623/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/speakers/logitech-z623/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T13:15:00.000Z",
            updatedAt: "2025-05-01T13:15:00.000Z",
            barcode: "5099206066298",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Âm thanh chất lượng rạp phim, bass rất mạnh.",
                reviewerName: "Minh Hiếu",
            },
        ],
    },
    {
        id: 149,
        title: "Netgear Nighthawk RAXE500 WiFi 6E Router",
        description:
            "Router Wi-Fi 6E ba băng tần, tốc độ cực nhanh, phạm vi phủ sóng rộng, lý tưởng cho gia đình thông minh.",
        brand: "Netgear",
        category: "networking",
        price: 499.99,
        discountPercentage: 20.0,
        rating: 4.5,
        stock: 30,
        availabilityStatus: "In Stock",
        sku: "NET-NET-RAXE500-149",
        minimumOrderQuantity: 2,
        returnPolicy: "90 days return policy",
        warrantyInformation: "1 year warranty",
        shippingInformation: "Ships in 3 business days",
        tags: ["electronics", "network", "router"],
        weight: 1450,
        dimensions: { width: 29.8, height: 21.0, depth: 8.0 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/networking/netgear-nighthawk-raxe500/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/networking/netgear-nighthawk-raxe500/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T13:20:00.000Z",
            updatedAt: "2025-05-01T13:20:00.000Z",
            barcode: "606449156424",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 4,
                comment: "Tốc độ rất nhanh, nhưng hơi đắt.",
                reviewerName: "Quang Minh",
            },
        ],
    },
    {
        id: 150,
        title: "Garmin Fenix 7 Pro Solar",
        description:
            "Đồng hồ thông minh GPS đa thể thao, sạc năng lượng mặt trời, màn hình MIP, nhiều tính năng chuyên nghiệp.",
        brand: "Garmin",
        category: "smartwatches",
        price: 899.99,
        discountPercentage: 10.0,
        rating: 4.7,
        stock: 20,
        availabilityStatus: "In Stock",
        sku: "SMW-GAR-F7PS-150",
        minimumOrderQuantity: 1,
        returnPolicy: "30 days return policy",
        warrantyInformation: "2 year warranty",
        shippingInformation: "Ships next day",
        tags: ["electronics", "wearables", "smartwatch", "outdoor"],
        weight: 79,
        dimensions: { width: 5.1, height: 5.1, depth: 1.49 },
        thumbnail:
            "https://cdn.dummyjson.com/product-images/smartwatches/garmin-fenix-7-pro-solar/thumbnail.webp",
        images: [
            "https://cdn.dummyjson.com/product-images/smartwatches/garmin-fenix-7-pro-solar/1.webp",
        ],
        meta: {
            createdAt: "2025-05-01T13:25:00.000Z",
            updatedAt: "2025-05-01T13:25:00.000Z",
            barcode: "753759296542",
            qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
        },
        reviews: [
            {
                rating: 5,
                comment: "Đồng hồ tuyệt vời cho hoạt động ngoài trời, pin rất lâu.",
                reviewerName: "Thanh Tùng",
            },
        ],
    },
];

export default products;